name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev libboost-all-dev libvulkan-dev libglm-dev

      - name: Check out repository
        uses: actions/checkout@v3.3.0

      - name: Configure and build
        uses: threeal/cmake-action@latest
        with:
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          run-test: true
